INFO:scrapy.utils.log:Scrapy 2.8.0 started (bot: saramin)
INFO:scrapy.utils.log:Versions: lxml 4.9.1.0, libxml2 2.9.12, cssselect 1.2.0, parsel 1.7.0, w3lib 2.1.1, Twisted 22.10.0, Python 3.8.13 (default, Oct 19 2022, 22:38:03) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 22.0.0 (OpenSSL 1.1.1n  15 Mar 2022), cryptography 36.0.2, Platform Windows-10-10.0.19045-SP0
INFO:scrapy.crawler:Overridden settings:
{'BOT_NAME': 'saramin',
 'DOWNLOAD_DELAY': 3,
 'FEED_EXPORT_ENCODING': 'utf-8',
 'HTTPCACHE_ENABLED': True,
 'NEWSPIDER_MODULE': 'saramin.spiders',
 'REQUEST_FINGERPRINTER_IMPLEMENTATION': '2.7',
 'SPIDER_MODULES': ['saramin.spiders'],
 'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'}
DEBUG:asyncio:Using selector: SelectSelector
DEBUG:scrapy.utils.log:Using reactor: twisted.internet.asyncioreactor.AsyncioSelectorReactor
DEBUG:scrapy.utils.log:Using asyncio event loop: asyncio.windows_events._WindowsSelectorEventLoop
INFO:scrapy.extensions.telnet:Telnet Password: ca5d9fdc292af52f
INFO:scrapy.middleware:Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
DEBUG:scrapy_fake_useragent.middleware:Loaded User-Agent provider: scrapy_fake_useragent.providers.FakeUserAgentProvider
INFO:scrapy_fake_useragent.middleware:Using '<class 'scrapy_fake_useragent.providers.FakeUserAgentProvider'>' as the User-Agent provider
INFO:scrapy.middleware:Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy_fake_useragent.middleware.RandomUserAgentMiddleware',
 'saramin.middlewares.SaraminDownloaderMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats',
 'scrapy.downloadermiddlewares.httpcache.HttpCacheMiddleware']
INFO:scrapy.middleware:Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
INFO:scrapy.middleware:Enabled item pipelines:
['saramin.pipelines.SaraminPipeline',
 'saramin.pipelines.MongoDBPipeline',
 'saramin.pipelines.JsonWriterPipeline']
INFO:scrapy.core.engine:Spider opened
INFO:scrapy.core.engine:Closing spider (shutdown)
ERROR:scrapy.core.engine:Scraper close failure
Traceback (most recent call last):
  File "C:\Users\ybnt\anaconda3\envs\job_scrap\lib\site-packages\scrapy\crawler.py", line 124, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
pymongo.errors.InvalidURI: ("Invalid URI scheme: URI must begin with '%s' or '%s'", ('mongodb://', 'mongodb+srv://'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ybnt\anaconda3\envs\job_scrap\lib\site-packages\twisted\internet\defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "C:\Users\ybnt\Desktop\개인프로젝트\job_scrap\ver3\saramin_skills\saramin\saramin\pipelines.py", line 70, in close_spider
    self.client.close()
AttributeError: 'MongoDBPipeline' object has no attribute 'client'
ERROR:scrapy.utils.signal:Error caught on signal handler: <bound method CoreStats.spider_closed of <scrapy.extensions.corestats.CoreStats object at 0x00000254D2CB4B50>>
Traceback (most recent call last):
  File "C:\Users\ybnt\anaconda3\envs\job_scrap\lib\site-packages\scrapy\crawler.py", line 124, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
pymongo.errors.InvalidURI: ("Invalid URI scheme: URI must begin with '%s' or '%s'", ('mongodb://', 'mongodb+srv://'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ybnt\anaconda3\envs\job_scrap\lib\site-packages\scrapy\utils\defer.py", line 312, in maybeDeferred_coro
    result = f(*args, **kw)
  File "C:\Users\ybnt\anaconda3\envs\job_scrap\lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "C:\Users\ybnt\anaconda3\envs\job_scrap\lib\site-packages\scrapy\extensions\corestats.py", line 30, in spider_closed
    elapsed_time = finish_time - self.start_time
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
INFO:scrapy.statscollectors:Dumping Scrapy stats:
{'log_count/DEBUG': 5, 'log_count/ERROR': 2, 'log_count/INFO': 9}
INFO:scrapy.core.engine:Spider closed (shutdown)
CRITICAL:twisted:Unhandled error in Deferred:
CRITICAL:twisted:
Traceback (most recent call last):
  File "C:\Users\ybnt\anaconda3\envs\job_scrap\lib\site-packages\twisted\internet\defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "C:\Users\ybnt\anaconda3\envs\job_scrap\lib\site-packages\scrapy\crawler.py", line 124, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
pymongo.errors.InvalidURI: ("Invalid URI scheme: URI must begin with '%s' or '%s'", ('mongodb://', 'mongodb+srv://'))
